// Weekly Report Template for "The Oracle That Wears Us"
// Auto-generated by GitHub Actions

#set page(
  paper: "a4",
  margin: (x: 50pt, y: 60pt),
)

#set text(
  font: "Noto Sans",
  size: 10pt,
  fill: rgb("#333333"),
  lang: "en"
)

// --- THEME DEFINITION (from Project02-Plan.typ) ---
#let chapter_themes = (
  "1": (
    grad_start: rgb("#2F80ED"),
    grad_end: rgb("#9B51E0"),
    accent: rgb("#33A1C9"),
    page_bg: rgb("#A5C7F3")
  ),
  "2": (
    grad_start: rgb("#eb3349"),
    grad_end: rgb("#f45c43"),
    accent: rgb("#e74c3c"),
    page_bg: rgb("#ff9a9e")
  ),
  "3": (
    grad_start: rgb("#11998e"),
    grad_end: rgb("#38ef7d"),
    accent: rgb("#1b5e20"),
    page_bg: rgb("#c8e6c9")
  ),
  "4": (
    grad_start: rgb("#F2994A"),
    grad_end: rgb("#F2C94C"),
    accent: rgb("#d35400"),
    page_bg: rgb("#fdebd0")
  )
)

#let muted_bg = rgb("#f4f4f4")

// --- REUSABLE COMPONENTS ---
#let report_header(ch_idx, category: "WEEKLY REPORT") = {
  let t = chapter_themes.at(ch_idx)
  move(dy: -20pt)[
    #box(
      width: 100%,
      height: 30pt,
      fill: gradient.linear(t.grad_start, t.grad_end),
      inset: (right: 15pt),
      align(right + horizon, text(white, weight: "bold", tracking: 1.5pt, size: 8pt)[#upper(category)])
    )
  ]
}

#let section_title(ch_idx, num, title) = {
  let t = chapter_themes.at(ch_idx)
  v(20pt)
  text(fill: t.accent, size: 22pt, weight: "extrabold")[#num]
  v(-12pt)
  text(fill: t.accent, size: 22pt, weight: "bold")[#upper(title)]
  v(20pt)
}

#let page_footer(ch_idx, num) = {
  let t = chapter_themes.at(ch_idx)
  place(
    bottom + right,
    dx: 30pt,
    dy: 30pt,
    square(
      size: 35pt,
      fill: t.page_bg,
      align(center + horizon, text(white, weight: "bold", size: 14pt)[#num])
    )
  )
}

#let status_badge(status) = {
  let colors = (
    "done": (bg: rgb("#38ef7d"), fg: rgb("#1b5e20")),
    "in-progress": (bg: rgb("#F2C94C"), fg: rgb("#d35400")),
    "blocked": (bg: rgb("#eb3349"), fg: white),
    "review": (bg: rgb("#33A1C9"), fg: white)
  )
  let c = colors.at(status, (bg: gray, fg: white))
  box(
    fill: c.bg,
    inset: (x: 8pt, y: 3pt),
    radius: 3pt,
    text(size: 8pt, fill: c.fg, weight: "bold")[#upper(status)]
  )
}

#let issue_row(issue) = {
  [
    #grid(
      columns: (1fr, auto),
      gutter: 10pt,
      [#issue.title],
      #status_badge(issue.status)
    )
  ]
}

#let completed_table(issues) = {
  if len(issues) > 0 [
    #table(
      columns: (1fr),
      inset: 8pt,
      stroke: 0.5pt + gray.lighten(50%),
      fill: (x, y) => if calc.even(y) { muted_bg.lighten(50%) },
      ..issues
    )
  ] else [
    _No completed issues this week._
  ]
}

#let in_progress_table(issues) = {
  if len(issues) > 0 [
    #table(
      columns: (1fr, auto),
      inset: 8pt,
      stroke: 0.5pt + gray.lighten(50%),
      fill: (x, y) => if y == 0 { muted_bg } else { if calc.even(y) { muted_bg.lighten(50%) } },
      [*Issue*], [*Status*],
      ..issues
    )
  ] else [
    _No issues in progress._
  ]
}

#let stats_box(stats) = {
  #grid(
    columns: (1fr, 1fr, 1fr, 1fr),
    gutter: 10pt,
    box(
      fill: chapter_themes.at("1").accent.lighten(90%),
      inset: 10pt,
      radius: 4pt,
      align(center, [
        #text(size: 18pt, weight: "bold", fill: chapter_themes.at("1").accent)[#stats.completed]]
        #text(size: 8pt)[Completed]
      ])
    ),
    box(
      fill: chapter_themes.at("2").accent.lighten(90%),
      inset: 10pt,
      radius: 4pt,
      align(center, [
        #text(size: 18pt, weight: "bold", fill: chapter_themes.at("2").accent)[#stats.in_progress]]
        #text(size: 8pt)[In Progress]
      ])
    ),
    box(
      fill: chapter_themes.at("3").accent.lighten(90%),
      inset: 10pt,
      radius: 4pt,
      align(center, [
        #text(size: 18pt, weight: "bold", fill: chapter_themes.at("3").accent)[#stats.blocked]]
        #text(size: 8pt)[Blocked]
      ])
    ),
    box(
      fill: chapter_themes.at("4").accent.lighten(90%),
      inset: 10pt,
      radius: 4pt,
      align(center, [
        #text(size: 18pt, weight: "bold", fill: chapter_themes.at("4").accent)[#stats.total]]
        #text(size: 8pt)[Total Issues]
      ])
    )
  )
}

// --- DOCUMENT CONTENT ---
#let week_num = input("week", default: 1)
#let report_date = input("date", default: datetime.today())
#let milestone_name = input("milestone", default: "1st milestone: Documentation")

// PAGE 1: COVER & SUMMARY
#report_header("1")

#section_title("1", f"Week {week_num}", "Weekly Progress Report")

#table(
  columns: (1fr),
  inset: 12pt,
  stroke: none,
  fill: muted_bg,
  [
    #grid(
      columns: (1fr, 1fr),
      gutter: 15pt,
      [
        *Report Date:* \ #report_date \ \
        *Milestone:* \ #milestone_name \ \
        *Week Period:* \ Week #week_num
      ],
      [
        *Project:* \ The Oracle That Wears Us \ \
        *Team:* \
        #grid(
          columns: (1fr, 1fr, 1fr),
          gutter: 5pt,
          [Nadine Allan],
          [Andrey Dyakov],
          [Dmitri Kazantsev]
        )
      ]
    )
  ]
)

#v(2em)

== Executive Summary

#input("summary", default: "This week, the team made significant progress on...")

#v(1em)
#stats_box(input("stats", default: (completed: 0, in_progress: 0, blocked: 0, total: 0)))

#v(2em)

== Key Achievements This Week

#input("achievements", default: "- Achievement 1\n- Achievement 2\n- Achievement 3")

#page_footer("1", "1")
#pagebreak()

// PAGE 2: COMPLETED WORK
#report_header("2")

#section_title("2", "2.0", "Completed Issues")

#input("completed_issues", default: completed_table((
  [Example completed issue #1],
  [Example completed issue #2]
)))

#v(2em)

== Notes & Observations

#input("completed_notes", default: "_Add any relevant notes about completed work..._")

#page_footer("2", "2")
#pagebreak()

// PAGE 3: IN PROGRESS & BLOCKED
#report_header("3")

#section_title("3", "3.0", "Work In Progress")

== Current Sprint

#input("in_progress_issues", default: in_progress_table((
  ([Issue title], [in-progress]),
  ([Issue title], [review])
)))

#v(2em)

== Blocked Issues

#input("blocked_issues", default: in_progress_table((
  ([Issue title], [blocked])
)))

#v(2em)

== Blockers & Challenges

#input("blockers", default: "_No major blockers this week._")

#page_footer("3", "3")
#pagebreak()

// PAGE 4: NEXT WEEK & MILESTONE TRACKING
#report_header("4")

#section_title("4", "4.0", "Next Week Plan")

== Planned Issues

#input("planned_issues", default: "- [ ] Issue #1\n- [ ] Issue #2\n- [ ] Issue #3")

#v(2em)

== Milestone Progress

#let milestone_progress = input("milestone_progress", default: 25)
#box(
  width: 100%,
  height: 20pt,
  fill: gray.lighten(80%),
  inset: 0pt,
  radius: 3pt,
  [
    #box(
      width: f"{milestone_progress}%",
      height: 100%,
      fill: gradient.linear(chapter_themes.at("1").grad_start, chapter_themes.at("1").grad_end),
      radius: 3pt
    )
  ]
)
#text(size: 8pt, fill: gray)[#milestone_progress}% complete towards #milestone_name]

#v(2em)

== Team Workload

#table(
  columns: (1fr, 1fr, 1fr),
  inset: 10pt,
  stroke: 0.5pt + gray.lighten(50%),
  fill: (x, y) => if y == 0 { muted_bg },
  [*Team Member*], [*Issues Completed*], [*Focus Area*],
  [Nadine Allan], [input("nadine_issues", default: "0")], [input("nadine_focus", default: "-")],
  [Andrey Dyakov], [input("andrey_issues", default: "0")], [input("andrey_focus", default: "-")],
  [Dmitri Kazantsev], [input("dmitri_issues", default: "0")], [input("dmitri_focus", default: "-")]
)

#v(2em)

== Risks & Decisions Needed

#input("risks", default: "_No major risks identified._")

#page_footer("4", "4")
